sql:
  enabled: true
  driver-class-name: "default"
bitwise:
  enabled: true
gui:
  enabled: true
runtime:
  enabled: true
requests:
  enabled: true
files:
  enabled: true
world:
  enabled: true
permissions:
  enabled: true
interpretate:
  enabled: true
string-utils:
  enabled: true
floodgate:
  enabled: true
viaversion:
  enabled: true
map:
  enabled: true
other:
  enabled: true
maps:
  enabled: true
sockets:
  enabled: false
  server-address: "127.0.0.1"
  server-port: 1337
  client-autoreconnect-time: 5