name: Skcrew
version: 1.5
main: com.lotzy.skcrew.Skcrew
description: Skript addon allows you make bedrock forms and some other
website: https://github.com/LotzyProd/Skcrew
depend: [Skript]
softdepend: [Floodgate, ViaVersion]
author: Lotzy
api-version: 1.13