name: Skcrew
version: 3.6
main: com.lotzy.skcrew.spigot.Skcrew
description: Skript addon allows you make bedrock forms, integration with proxy, handle packets and some other
website: https://github.com/crewpvp/skcrew
depend: [Skript]
softdepend: [Floodgate, ViaVersion]
authors: [Lotzy, w0w0, Olyno, Govindas, APickledWalrus, MrsDarth, Pesekjak]
api-version: "1.13"