name: Skcrew
version: 3.0
main: com.lotzy.skcrew.spigot.Skcrew
description: Skript addon allows you make bedrock forms, integration with proxy and some other
website: https://github.com/crewpvp/skcrew
depend: [Skript]
softdepend: [Floodgate, ViaVersion]
author: Lotzy